baseURL = "/#/"
languageCode = "en-us"
title = "Kim Haroche"
theme = "hugo-arcana"
copyright = "© Kim Haroche, Stillness in Movement LLC, 2024"

defaultContentLanguage = "en"

[taxonomies]
    tag = "Pilates, Kim Haroche, Therapist, Pilates Instructor"

[params]
    description = "Kim Haroche"
    show_post_dates = false

    [params.footer]

        [[params.footer.links]]
            header = "Get in Touch"
        [[params.footer.links.links]]
            title = "Mattis et quis rutrum"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse amet varius"
            url = "#"
        [[params.footer.links]]    
            header = "Get in Touch"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan dolor"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis rutrum accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse varius nibh"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus mattis"
            url = "#"

        [[params.footer.links]]
            header = "More Links to Stuff"
        [[params.footer.links.links]]
            title = "Duis neque nisi dapibus"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis et sed accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Duis neque nisi sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum amet varius"
            url = "#"
