baseURL = "https://kimharoche.netlify.app/"
languageCode = "en-us"
title = "Kim Haroche"
theme = "hugo-arcana"
copyright = "© Kim Haroche, Stillness in Movement LLC, 2024"

defaultContentLanguage = "en"

[taxonomies]
    tag = "Pilates, Kim Haroche, Therapist, Pilates Instructor"

[params]
    description = "Kim Haroche"
    show_post_dates = false

    [params.footer]

        [[params.footer.links]]
        [[params.footer.links.links]]
            title = "Home"
            url = "/#"
        [[params.footer.links.links]]
            title = "About"
            url = "/about/"
        [[params.footer.links]]    
        [[params.footer.links.links]]
            title = "Counseling Services"
            url = "/counseling-services/"
        [[params.footer.links.links]]
            title = "Cranial Sacral Therapy"
            url = "/cranio/"
        [[params.footer.links]]
        [[params.footer.links.links]]
            title = "Pilates"
            url = "/pilates/"
        [[params.footer.links.links]]
            title = "Contact"
            url = "/contact/"
