[[main]]
    name = "About"
    url = "/about/"
    weight = 25
[[main]]
    name = "Counseling Services"
    url = "/counseling-services/"
    weight = 30
[[main]]
    parent = "Counseling Services"
    name = "Couples"
    url = "/counseling-services/couples"
    weight = 31
[[main]]
    parent = "Counseling Services"
    name = "Individuals"
    url = "/counseling-services/individuals"
    weight = 32
[[main]]
    parent = "Counseling Services"
    name = "Trauma"
    url = "/counseling-services/trauma"
    weight = 33

[[main]]
    name = "Cranial Sacral Therapy"
    url = "/cranio/"
    weight = 41

[[main]]
    parent = "Cranial Sacral Therapy"
    name = "People"
    url = "/cranio/#for-people"
    weight = 42

[[main]]
    parent = "Cranial Sacral Therapy"
    name = "Animals"
    url = "/cranio/#for-animals"
    weight = 43

[[main]]
    name = "Pilates"
    url = "/pilates/"
    weight = 50

[[main]]
    parent = "Pilates"
    name = "Workshops"
    url = "/workshops"
    weight = 51
[[main]]
    parent = "Pilates"
    name = "Mentoring Groups"
    url = "/pilates/#mentoring-groups"
    weight = 52
[[main]]
    parent = "Pilates"
    name = "Privates"
    url = "/pilates/#private-lessons"
    weight = 53
[[main]]
    name = "Contact"
    url = "/contact/"
    weight = 80