baseURL = "https://example.org/"
languageCode = "en-us"
title = "Kim Haroche"
theme = "hugo-arcana"
copyright = "© Kim Haroche, Stillness in Movement LLC, 2024"

defaultContentLanguage = "en"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.de]
        languageName = "Deutsch"
        weight = 2

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    show_post_dates = false

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "#"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "#"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"
    [params.footer]

        [[params.footer.links]]
            header = "Explore"
        [[params.footer.links.links]]
            title = "Counseling Therapy"
            url = "/counseling-services/"
        [[params.footer.links.links]]
            title = "Cranial Sacral Therapy"
            url = "/cranial-sacral-therapy/"
        [[params.footer.links.links]]
            title = "Pilates"
            url = "/pilates/"
        [[params.footer.links.links]]
            title = "About"
            url = "/about/"
        [[params.footer.links.links]]
            title = "Contact"
            url = "/contact/"

        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = ""